version: '2'
services:
  frontend:
    build: frontend
    depends_on:
      - varnish
    restart: always
    ports:
      - "0.0.0.0:39080:80"
  api:
    build: backend
    restart: always
  varnish:
    image: varnish:7.3.0
    depends_on:
      - api
    restart: always
    environment:
      - VARNISH_HTTP_PORT=7777
    volumes:
      - $PWD/varnish/default.vcl:/etc/varnish/default.vcl:ro
