version: '2'
services:
  frontend:
    build: frontend
    depends_on:
      - varnish
    restart: always
    ports:
      - "0.0.0.0:39088:80"
    volumes:
      - $PWD/frontend/html:/usr/share/nginx/html
  api:
    build: backend
    restart: always
    environment:
      - DEBUG=True
      - PYTHONUNBUFFERED=1
    volumes:
      - $PWD/backend/utils.py:/app/utils.py
      - $PWD/backend/main.py:/app/main.py
  varnish:
    image: varnish:7.3.0
    depends_on:
      - api
    restart: always
    environment:
      - VARNISH_HTTP_PORT=7777
    volumes:
      - $PWD/varnish/default.vcl:/etc/varnish/default.vcl:ro
